### ISSUE TITLE
How to send emoji in message. and also need list of emoji codes.

### ISSUE THREAD

**Issue by SSinfo302** [JicuNull/WhatsJava#16]
How to send emoji in message. and also need list of emoji codes.

please provide list and give example to send emoji.

**Comment by JicuNull** [comment]
Just use any unicode [table](https://unicode.org/emoji/charts/full-emoji-list.html) and use your desired emoji inside of the sendMessage method.

`client.sendMessage("49123456789@c.us", "🙂");`

You may also have look [here](https://medium.com/swlh/how-to-easily-handle-emoji-unicode-in-java-ff905f264f98)
