### ISSUE TITLE
Add Feature Clean

### ISSUE THREAD

**Issue by syifarahmat** [JicuNull/WhatsJava#4]
Add delete message feature and clean messages in chat 😄

**Comment by JicuNull** [comment]
I made a small update and added a clearMessage method that deletes a message for yourself. Deleting a message for everyone in the chat is not implemented for the time being, as this takes more time than I currently have :wink:

I hope this helps you

**Comment by syifarahmat** [comment]
Thank you so much for already .... Good job, your dedication really helps 🙏🙏🙏🙏👍👍👍👍👍👍
