### ISSUE TITLE
Help To Encrypt Media

### ISSUE THREAD

**Issue by syifarahmat** [JicuNull/WhatsJava#7]
Can you help me to create a function to encrypt media to be sent as picture / document / video / audio messages?

Thank you

**Comment by syifarahmat** [comment]
please correct my logic
![image](https://user-images.githubusercontent.com/11779955/96562341-dd564d80-12ea-11eb-9328-1941eda7b16c.png)
🙏🙏🙏

**Comment by syifarahmat** [comment]
Please help for Encrypt file to send....
I success send file/image/audio/etc.... but can't open because my encrypt method fails & cant't decrypt 🙏🙏🙏🙏🙏🙏

**Comment by JicuNull** [comment]
Hey,
sorry for not answering sooner, but I'm busy with exams and some other things. I might look into it, when I have some spare time at the weekend, if you still need help.

**Comment by syifarahmat** [comment]
Thanks brother. After I studied it, finally I was able to develop your library and add quite a number of changes in between. send contact, send image, send document, send video, send sticker, send location and receive all contacts, images, etc ...

Thank you. 👍👍👍👍🙏🙏🙏🙏🙏
