### ISSUE TITLE
Sending Media message

### ISSUE THREAD

**Issue by karthikeyan-krishna** [JicuNull/WhatsJava#8]
Hi, 
How to send media like Images, Document, Videos, etc?

**Comment by zhengshengjie666** [comment]
你好，请问如何发送图片、视频、文档？

Hi,
How to send media like Images, Document, Videos, etc?

**Comment by karthikeyan-krishna** [comment]
I have come up with my own Implementation, that supports sending Images, Videos
Try it

https://github.com/karthikeyan-krishna/JavsApp
